# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25d46987f7cf05f7b4ba30e696535a01f58a1292fa65ceed27553363fe994c510c6644cbb07a6df6407e7c477bcd833022dd8c7c3eaf77e7dd7836a4f06336f5

test:
  secret_key_base: b1ded25fd50e29de35cac111c9e2a241591f5c4fe084a32b443f022f29448c6bd3b698c66e32d303e213c827b9833a4787a03fbb2c22ac031a173b222d053aaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
